# Render Blueprint for Esther AI Trading Agent

services:
  # A Python web service to keep the bot alive on Render's free tier
  - type: web
    name: esther-bot
    env: python
    plan: free # Specifies the free instance type
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python src/main.py"
databases:
  # A PostgreSQL database on the free plan
  - name: esther-db
    plan: free
