# Render Blueprint for Esther AI Trading Agent

services:
  # A Python web service to keep the bot alive on Render's free tier
  - type: web
    name: esther-bot
    env: python
    plan: free # Specifies the free instance type
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python run.py"
    envVars:
      # The DATABASE_URL is automatically provided by Render from the linked database service.
      - key: DATABASE_URL
        fromDatabase:
          name: esther-db # This should match the name of your Render PostgreSQL database
          property: connectionString
      # Non-secret environment variables can be defined here.
      - key: PYTHON_VERSION
        value: 3.11.7 # Specify a major, minor, and patch version
      # IMPORTANT: All other secrets (TELEGRAM_BOT_TOKEN, GEMINI_API_KEY, etc.) 
      # must be added as a Secret File in the Render dashboard's "Environment" tab.

databases:
  # A PostgreSQL database on the free plan
  - name: esther-db
    plan: free
